### ISSUE TITLE
Account creation with unlisted organisation is broken

### ISSUE THREAD

**Issue by Sudiukil** [DMPRoadmap/roadmap#1770] opened 2018-08-02 12:32 UTC
**Expected behaviour:**

Users should be able to create an account even if their organisation is not listed by using the "My organisation isn't listed" link and entering an organisation name manually.

**Actual behaviour:**

Using the "My organisation isn't listed" link an entering a name manually is possible but the form is then considered invalid and won't be submitted (see screenshot below).

![2018-08-02-142806_364x707_scrot](https://user-images.githubusercontent.com/5354318/43583749-c2ac1d88-9660-11e8-9fec-297a6a50b38c.png)

**Steps to reproduce:**

1. Access DMP OPIDoR sign-in/up page
2. Fill in the "Create account" form
3. Click the "My organisation isn't listed"
4. Fill the second field with an arbitrary value
5. Click the submit button

**Comment by Sudiukil** [comment] 2018-08-02 13:42
Another weird thing: I found a potential fix on a [6-months old commit](https://github.com/DMPRoadmap/roadmap/commit/ed940aa812d13ea739e2bab27a38dce1f7ea7ac0#diff-279f881a6e2c74241da5f8d76791d215R11) but somehow these changes where removed since. They are absent from both master and development branches... **but** they are present on our DMP OPIDoR fork... it's not working but it's there, I'm confused about why.

**Comment by xsrust** [comment] 2018-08-02 14:02
Hi,
Do you have an 'Other' org in your database?
If you have an organisation with the is_other flag set to true? 
The code checks for an 'other_org_id' here:
https://github.com/DMPRoadmap/roadmap/blob/master/app/views/shared/_my_org.html.erb#L16

**Comment by Sudiukil** [comment] 2018-08-02 14:18
Yes, having such an organisation in my database "solves" the issue and allows me to create the account.

But that does not quite solve the issue for me, not having an "Other" organisation (with 'is_other' == true) in the database should yield this error:

![2018-08-02-161606_1151x64_scrot](https://user-images.githubusercontent.com/5354318/43589614-5fd47390-966f-11e8-8cda-e9b9798b4125.png)

... and not a form error suggesting it was filled incorrectly (which is wrong in that case, the user filled the form as required).

**Comment by Sudiukil** [comment] 2018-08-02 14:30
The easiest option might be to simply remove the 'My organisation isn't listed' or change it's effect when it's actually not possible to create an account with an unlisted org.

Either way I can work on the issue and make a PR, I just need to know how you want me to approach this.

**Comment by xsrust** [comment] 2018-08-02 14:48
I think submitting the form without an org, checking for no org in the controller and attempting to set the org to the `is_other: true` one in the db would work, with the error you listed above if there's no other org.

@briri, @stephaniesimms and @sjDCC  can weigh in as well though
The field may need to be manditory for accessibility concerns

Thanks for working on this!

**Comment by briri** [comment] 2018-08-02 14:55
Hi @Sudiukil. I like the idea you have proposed for adding a clearer error message so that the user knows that the issue is not do to bad data entry on their part. 

For the [DMPTool](https://dmptool.org) implementation we have removed that link and the 'other' org textbox completely.
![screen shot 2018-08-02 at 7 48 48 am](https://user-images.githubusercontent.com/1204467/43591648-9f560124-9628-11e8-85a5-471482762282.png)

Unfortunately the system relies heavily on the User's relationship to Org so we need to continue to attach users to the `is_other=true` org. If you're interested I would be happy to share the customization from the screenshot above. If its useful for both of our organizations it may make sense for us to contribute the code back to the core Roadamap project as a configurable option.

@xsrust we may want to consider adding a rake task that inserts an `is_other` org and some instructions on the installation wiki page. We should likely add instructions about setting the default template as well.

**Comment by sjDCC** [comment] 2018-08-02 15:33
Thanks for flagging this @Sudiukil 

I'd be good to know how the potential fix from the 6 month old commit worked as we had fixed this in the past but things seem to have changed since. Perhaps as we have variant code / approaches here? 

Here's how I think it should work. @stephaniesimms can chime in to confirm too.

1. The user should be able to select 'Other' from the controlled dropdown list of organisations. Doing so should open up a box to fill in the name of that other org

OR

2. The user should be able to click 'My org isn't listed' and this should set the dropdown to 'Other' and display the box to fill in the org name

It's useful for us to capture the other orgs to track who is using the tool so I'd like to keep this field. At the moment it is only clicking 'my org isn't listed' that opens up that text box. Selecting 'Other' org doesn't. Also, the dropdown isn't defaulting to 'Other' when you click to say the org isn't listed.

**Comment by Sudiukil** [comment] 2018-08-02 15:37
@sjDCC Your second proposal could actually be the simplest option and I found something related on [this issue](https://github.com/DMPRoadmap/roadmap/issues/1729), I missed that earlier.

**Comment by sjDCC** [comment] 2018-08-02 15:40
Thanks @Sudiukil 

Ideally users would be able to do both as some people will look for 'Other' org in the list but if that's overkill I'd be happy the second option only.

**Comment by stephaniesimms** [comment] 2018-08-02 16:12
@sjDCC - I'm agnostic regarding the implementation in roadmap since dmptool has a customized approach to Org selection as @briri mentioned above.

**Comment by sjDCC** [comment] 2018-08-02 22:14
Ok, let's revert to how it was before then if that works for folks i.e. 

The user should be able to select 'Other' from the controlled dropdown list of organisations. Doing so should open up a box to fill in the name of that other org
and
The user should be able to click 'My org isn't listed' and this should set the dropdown to 'Other' and display the box to fill in the org name

With any luck that will be in the old code @Sudiukil found and can just be reinstated. It should prevent the error messages occurring.

**Comment by Sudiukil** [comment] 2018-08-02 22:48
@sjDCC In any case I'll have a look at it and I can reimplement it if needed!

**Comment by Sudiukil** [comment] 2018-08-03 10:14
[a couple lines of code later...]

Clicking 'My organisation isn't listed' and entering a name now selects automatically the 'Other' organisation.

Although I wonder if it's a good idea to add the possibility to select 'Other' directly in the combobox and then make the field appear, it seems confusing to me to have this "meta" organisation directly accessible in the combobox.

Anyway, there is still an issue: if there is no 'Other' organisation at all in the database, the 'Organisation' field will remain empty and the original issue won't be solved.

IMHO the best solution would be to remove the 'required' attribute of the Organisation field and check its presence in a more "smart" way using Javascript (that's what the old code I found seems to do, actually). This would allow the form submission with an empty field (if not 'Other' org exists), which would trigger the error message I mentioned in a [comment above](https://github.com/DMPRoadmap/roadmap/issues/1770#issuecomment-409942600).

**Comment by sjDCC** [comment] 2018-08-03 11:42
If the devs are happy not to have 'other' as an entry in the combobox list that's fine with me. I think it's how the US system works from what is described above so perhaps that could become part of the main code rather than a derivative? 

It sounds like it could be a common error for new installations not to have an 'other' entry in the database so the error message you received would recur. Best to avoid that if we can.

I would like to keep the 'Other' text box though as that info can be useful.

Thanks @Sudiukil!

**Comment by Sudiukil** [comment] 2018-08-03 14:33
A few screenshots to describe how it works now (see the PR for a changelog):

**Case 1: the form was not filled correctly**

![1 - true form error](https://user-images.githubusercontent.com/5354318/43648102-c65d6c00-9739-11e8-8add-81f4d870c732.png)

Happens when:
- 'Organisation' field was left empty
- Both 'Organisation' and 'Other organisation name' were left empty

**Case 2: No 'Other' org exists in the database**

![2 - no other org form](https://user-images.githubusercontent.com/5354318/43648340-69100854-973a-11e8-841d-8737a14b73da.png)

In that case, the 'Organisation' field won't be auto-filled with the 'Other' org name (since it does not exist), the user will be able to submit the form nonetheless and will receive the appropriate error message right after:

![3 - no other org error](https://user-images.githubusercontent.com/5354318/43648344-6d7bbd48-973a-11e8-85b3-bdad70771b78.png)

**Case 3: 'Organisation' field is automatically filled**

![4 - auto other if present](https://user-images.githubusercontent.com/5354318/43648361-841742de-973a-11e8-883c-5b66a8ccfc1d.png)

Happens when the user has clicked the 'My organisation isn't listed' link, has entered a name **and** when an 'Other' organisation exists. If so, the user will create is account successfully.

**Comment by sjDCC** [comment] 2018-08-03 15:06
This looks great, thanks @Sudiukil! 

If we could avoid option 2 that would be best as users won't always necessarily know who the system admins are. Can we add 'other' to the list by default or make it non-mandatory? I think the US change allows account creation with this field blank so maybe that addition helps here?

**Comment by briri** [comment] 2018-08-07 18:13
I have added 2 additional bullets to the 'Post Installation' instructions on our wiki to help prevent others from running into this issue for new installations.

**Comment by stephaniesimms** [comment] 2018-10-22 17:42
this should be fixed and included in the next release. closing provisionally but leaving on the board to confirm.

**Closed by stephaniesimms** 2018-10-22 17:42 UTC
Labels: bug
