### ISSUE TITLE
General layout/styling issues 

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#424] opened 2017-06-15 16:26 UTC
Please record any styling/layout changes that should be made to the newly re-branded site (currently deployed on roadmap-dev and roadmap-stg)

Note any color and font changes, positioning of error/informational messages, etc.

**Comment by rhu001** [comment] 2017-06-15 19:29
Note: @briri @stephaniesimms @JEK-III  and I met on 6/15 and discussed that we want to wait until more of the functionality is baked in before doing another round of graphic design changes. This round was just to set a baseline and see how we feel about a cleaner all white background. We'll be experimenting with different colors for the heading as we go. Do however, feel free to add comments about wishlist items moving forward.

**Comment by briri** [comment] 2017-06-15 22:22
related to #127 which contains initial specs

**Comment by briri** [comment] 2017-06-16 22:10
Agreed and that request is tied to #175. Rails has 2 message streams, one for notices and another for errors. We're not using the appropriate ones in all cases so whoever updates the placement and styling of these messages should also make sure we're using the appropriate `flash[:notice]` or `flash[:alert]`

**Comment by sjDCC** [comment] 2017-06-28 00:21
Had made comments about this before seeing this ticket. See #475 

Also just spotted an example on homepage where we need more whitespace between error message and top banner.
![whitespace-needed](https://user-images.githubusercontent.com/6169940/27615360-7eafab56-5b9f-11e7-856b-b81dfe2707d3.PNG)

I'm happy with the banner at the top, but this does have implications for our logo so we'll need to reflect on that for our styling. We should probably also suggest unis use a white version.

I wonder if we want a bottom banner to even out display. That's something I like in the Melbourne branding, see: https://dmp.research.unimelb.edu.au/en-UK/about_us

@dsisu can you take a look and chip in comments here too please as you've done most of the styling work on our end.

**Comment by stephaniesimms** [comment] 2017-06-29 19:30
Re institutional branding and the top banner display I'll cross-reference related issue #156 
@rhu001 is still working on wireframe options for this, but I think we all liked Weiwei's approach to replacing the Portage logo (or in this case roadmap) logo w/the institutional logo if admins upload one. Let us know what you think about it and/or if you always want to display the DMPonline logo somewhere in top banner?

**Comment by briri** [comment] 2017-06-29 20:18
@rhu001 For reference, here's what it looks like currently after the CSS rebuild. This particular logo happens to have a lot of extra white space on the right hand side. We would need to use logos with a white background like this. Logos with transparent logos get lost on the grey bar

![screen shot 2017-06-29 at 1 15 40 pm](https://user-images.githubusercontent.com/1204467/27708316-5d5c245a-5ccd-11e7-9e54-8cbde50a1be1.png)

**Comment by sjDCC** [comment] 2017-06-29 20:34
Maybe this is a reason not to have a top banner? In general I'm for it, but if transparent logos get lost so people have to upload ones with a white background, the institutional branding is going to look a bit crummy. That was actually one of the things I had against our grey background. Logos with white surrounds looked really blocky on it.

@stephaniesimms regarding institutional logos, I think the Portage approach of replacing the DMPonline / DMPTool / DMPRoadmap logo with their own one is good. Institutions would definitely like that. Only quibble is contextualisation. On Portage they have a strapline which remains. Perhaps we need to introduce something like this so it's clear what the service does when it's been customised. How about "Create, review, and share data management plans" or something of that ilk.

@dsisu what are your views on all this? What do you feel our users would like?

For reference here are some shots from Portage - pre login
![strapline](https://user-images.githubusercontent.com/6169940/27709047-ab5d8f32-5d12-11e7-9430-b9ad77b43d82.PNG)

And post login, when an institutional logo has been uploaded
![portage-strapline](https://user-images.githubusercontent.com/6169940/27709080-bef907a6-5d12-11e7-8567-4a5b9eacb620.PNG)

**Comment by rhu001** [comment] 2017-07-05 23:45
@briri @sjDCC We could potentially do an all white background for the top header area and that would take care of the color issue. I'd like to clarify... is the University of Edinburgh logo example with the two side by side logos be a real case or were you just plopping that in to show me what that logo looked like? If so, there is a potential dimension issue as well in that space if we need to account for two side by side logos.

**Comment by briri** [comment] 2017-07-06 14:33
@rhu it was just an example of what the logos would look like under the current method used to display institutional logos. There are others that do not have the extra white space but I don't have access to them all.

**Comment by sjDCC** [comment] 2017-07-06 16:01
Hi @rhu001 this is an example of what it looks like in the current model. The proposal is to have the institutional logo replace the DMPTool / DMPonline / DMProadmap logo. Currently it just sits next to it. The issue is making sure institutional logo works on banner and has context. I've suggested we keep a strapline like Portage

**Comment by stephaniesimms** [comment] 2017-07-06 16:25
@rhu001 to follow on comments above, if we all like the proposal to handle institutional branding by replacing the logo it's probably easier to do an all white background for the top header. this will accommodate institutional logos that tend to be color on white and save us the extra styling effort of supporting custom CSS like weiwei does. 

and yes to what @sjDCC said about message styling. i assume we want to distinguish between status and error msgs somehow (e.g., color) but display them in a consistent location. am happy to follow whatever you recommend.

**Comment by briri** [comment] 2017-07-07 17:58
Updated the header so that the background is white and when the user is logged in it will display their institution's logo if one is present otherwise it displays the roadmap logo.

We will unfortunately need to re-upload the logos because our upload process resized them to fit in the old location and they are blurry when we increase the size and display them where the roadmap logo is.

Here is what it looks like with the roadmap logo on the home page. I feel like we should have a line or something that runs across the page. The explore dropdown feels like its just floating out there.
![screen shot 2017-07-07 at 10 53 54 am](https://user-images.githubusercontent.com/1204467/27970217-da89dcfc-6302-11e7-8be7-57b2f2faca11.png)

And here is what it looks like with an institutional logo. This Univ. of Edinburgh logo has a lot of white space around it, there are likely better options out there for it.
![screen shot 2017-07-07 at 10 53 18 am](https://user-images.githubusercontent.com/1204467/27970278-23a77354-6303-11e7-91c8-6ccb10f37b14.png)

**Comment by rhu001** [comment] 2017-07-11 16:10
@briri Are the two logos in place bottom aligned with the global nav?

**Comment by dsisu** [comment] 2017-07-13 16:39
Hi all, sorry I haven't had the time to comment on the proposed new styling, I've been away. I need time to take a look at the wireframes. As discussed at our UX meeting yesterday, we should also carry out usability testing before we roll out any changes.

**Comment by stephaniesimms** [comment] 2017-07-13 22:51
Just to clarify the conversation from the UX mtg on 12 Jul: usability testing is built into the MVP roadmap and planned for after the accessibility retest on 31 Jul. Styling and branding are handled independently for each of our services. This ticket pertains to generic layout and styling for the DMPRoadmap codebase, which is what others will see when they download and install the tool.

**Comment by dsisu** [comment] 2017-07-14 13:43
I understand this. We applied our own styling to the proposed generic tool and the end-result isn’t great. I guess this is work in progress so I’m not too concerned about the DIY look of the current generic tool. The one thing that does concern me is the introduction of new elements on the page e.g. Explore. This is not a matter of styling and will have a big impact on the way people navigate the site. I’m not convinced this is more user-friendly than what we currently have and I don’t think it’s justified by accessibility either. We should not introduce changes like these without testing first. Also, accessibility and usability are not incompatible with good looks. It is important that we produce a well finished, professional looking generic tool that will entice organisations to download it and use it. I guess I’m preaching to the converted. I have other work to do now, I’ll look at the proposed wireframes next week and get back to you by Wednesday next week. Have a good weekend! #161

**Comment by briri** [comment] 2017-07-18 20:45
Copied over from issue #491 since they deal with site-wide styling changes:
- Remove boldface for field names in all plan creation (for multiple templates from same funder), writing, sharing, etc pages
- Remove colon after each field name
- Be consistent w/capitalization of every word for field names "Project Title" (or just first word, but we should pick one)
- update css to use the text '(required)' instead of '*' when the label has `class="required"`
-  standardize the width(s) for entry boxes, ideally make them the same as wireframes which present 2 different sizes

**Comment by briri** [comment] 2017-07-20 16:38
@sjDCC pointed out that the Page title's and descriptions are not lined up with the main content of the page. We can likely fix this sitewide via CSS

**Comment by sjDCC** [comment] 2017-07-24 14:57
We discussed how to handle institutional logos today and have a suggestion to make. We'd prefer not to lose the DMPonline one completely, but don't feel two logos work well side-by-side so in effect agree with the decision to replace this with the institutional one. What we'd propose as an addition is switching the DMPonline logo to be an icon at the start of the menu. We started to mock-up a visual of this. Will try to add a screengrab before calls.

One change layout wise would be dropping the menu beneath the primary logo rather than it running adjacent to it (bottom aligned) as this would allow for different sizes (square, landscape orientation etc) of uni logos more easily

**Comment by vyruss** [comment] 2017-07-24 15:41
@sjDCC mockup:
![image](https://user-images.githubusercontent.com/18707439/28531480-e22b795e-708e-11e7-945d-73af90b80605.png)

**Comment by sjDCC** [comment] 2017-07-24 15:42
Perfect, thanks @vyruss

**Comment by briri** [comment] 2017-07-24 16:26
@sjDCC and @stephaniesimms are no longer bold and do not have a colon after them.

**Comment by briri** [comment] 2017-07-27 18:11
fixed capitalization issue on profile tabs, create plan and edit project details pages. Changes are currently in PR

**Comment by sjDCC** [comment] 2017-08-10 12:23
Adding two wireframes agreed on UX call on 9th August as general layout for header / footer etc. This covers items we've been discussing under global nav and institutional branding. 

The wireframes marry together ideas shared by @rhu001 with some alternative suggestions based on the concerns we raised about header depth and multiple menu bars.

![home](https://user-images.githubusercontent.com/6169940/29170117-061fe352-7dcf-11e7-990c-e1408acd4adb.PNG)

![logged-in](https://user-images.githubusercontent.com/6169940/29170122-0a65cd32-7dcf-11e7-9fc1-1f88c29b8857.PNG)

**Comment by sjDCC** [comment] 2017-11-07 17:02
Superseded by bootstrap work. closing out

**Closed by sjDCC** 2017-11-07 17:02 UTC
Labels: MVP, ux
