### ISSUE TITLE
Creating plans for funders without templates

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#387] opened 2017-05-31 12:57 UTC
Hi, I created a plan for Hartstichting (Dutch Heart Foundation). They don't have a template yet but I was given the DCC generic template. I am told something has changed in the functionality so the programme logic now says that, if a funder doesn't have a template, user gets generic template. Was this intended?

**Comment by xsrust** [comment] 2017-05-31 13:02
It looks like what's happening is that the list of funders on the create plan page is a list of all funders, regardless of whether or not they have any published templates.

Upon submitting a plan creation request with a funder selected who does not have a template (in this case Hartstichting), instead of giving an error, a plan is created based off the generic template.

If this is not desired functionality, the problem can be solved by filtering the funders displayed on the create plan page

**Comment by vyruss** [comment] 2017-05-31 13:05
@sjDCC is this the intended behaviour?

**Comment by sjDCC** [comment] 2017-05-31 17:51
Previously we used to filter the funder list to only display those who had a published template. With the fundref integration though, we will be listing more than those who have customised this tool. With this in mind, I think the new logic that "if a funder doesn't have a template, user gets generic template" is best. It's still useful for us to know the funder, even if they don't have a template.

@stephaniesimms do you agree? If so we can just close this one out as no action is needed.

**Comment by stephaniesimms** [comment] 2017-05-31 22:53
This is the new logic we talked about for fundref integration, yes. it's also marked for usability testing to make sure everything is clear to users. i asked @JEK-III and @briri about filtering the list to only include funder names that have corresponding templates and i think they said it's not possible or overly complicated to do so. does my memory serve guys?

**Comment by briri** [comment] 2017-06-01 15:22
It would be easy to filter the current list as @xsrust noted above.

Crossref will be a bit trickier. I have not looked at their API yet to determine what information is available. We will need to tie whatever identifier they use to distinguish their orgs to our own records (like we are doing now for users and their orcids and shib ids). It will be too unreliable to rely on matching by name. We could have 'National Aeronautics and Space Administration' in our system and they might have 'NASA' in theirs so it would be difficult to confirm a match programmatically.

**Comment by stephaniesimms** [comment] 2017-06-01 17:31
I think we should filter it for now then per @xsrust comment and reconsider later when we implement Crossref API. at that point we can ask UX to give some input too. what do you think @sjDCC ?

**Comment by sjDCC** [comment] 2017-06-02 10:17
That sounds fine to me. @vyruss can we make that adjustment in mvp 0.3

**Comment by vyruss** [comment] 2017-06-07 18:45
@sjDCC done

**Comment by sjDCC** [comment] 2017-06-08 10:22
Checked and working. Thanks. Closing out

**Closed by sjDCC** 2017-06-08 10:22 UTC
Labels: DMPonline-test, MVP-v0.3
