### ISSUE TITLE
Create plan error

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#267] opened 2017-04-25 11:38 UTC
I've just tried creating a plan and got the error below
![capture](https://cloud.githubusercontent.com/assets/6169940/25383401/ddf5537c-29b3-11e7-8bef-e743adc0170b.PNG)

This was on an account I have just created by sharing a plan with my personal account, so perhaps it's because there is no organisation or any other affiliation to draw in automatically?

When I shared the plan and logged in under the new account, I was taken straight to the my plans table, not edit profile as a usual first time login would be directed.

**Comment by sjDCC** [comment] 2017-04-25 11:46
This must be linked to a user not having an organisation. I added a university affiliation to this account and plans now create fine.

**Comment by vyruss** [comment] 2017-04-25 11:52
Possible duplicate of #257

**Comment by sjDCC** [comment] 2017-04-25 11:54
Yes, looks like it is. Thanks for spotting @vyruss

**Comment by jollopre** [comment] 2017-04-26 16:11
This issue has been solved in #257

**Comment by stephaniesimms** [comment] 2017-05-01 17:44
Working as expected, although see new issue #285 . Closing this one.

**Closed by stephaniesimms** 2017-05-01 17:44 UTC
Labels: bug, MVP-v0.3
