### ISSUE TITLE
User cannot amend institutional affiliation under 'edit profile'

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#324] opened 2017-05-19 11:37 UTC
I tried to change my institution and on clicking save, I got the 404 error. Checking back via super admin, the amendment had not been correctly saved. I could only edit via superadmin.
![capture](https://cloud.githubusercontent.com/assets/6169940/26246234/ee51c66c-3c8f-11e7-9d74-87775a6fae23.PNG)

It feels like we've fixed this before. Maybe via #171?

**Comment by vyruss** [comment] 2017-05-19 12:03
caused by me restarting nginx. closing

**Closed by vyruss** 2017-05-19 12:03 UTC
Labels: bug, user
