### ISSUE TITLE
Super Admin: ActiveAdmin replacement

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#132] opened 2017-03-02 13:20 UTC
We need to replace ActiveAdmin with something simpler, more minimal, and preferably without a DSL to learn.

How does https://github.com/thoughtbot/administrate look?
Demo: https://administrate-prototype.herokuapp.com/admin

**Comment by vyruss** [comment] 2017-03-03 17:48
Fixed by b54c1cf3e3d35a53ddaacb4e5ae202191e1d7d66 ? =)

**Comment by briri** [comment] 2017-03-06 18:42
I think we should only build out the controllers for the 2 use cases @sjDCC mentions in #131 and the few lookup tables we maintain (e.g. identifier_schemes, languages, etc.).

**Comment by briri** [comment] 2017-03-17 18:02
re-opening because it has not yet been part of a PR

**Comment by stephaniesimms** [comment] 2017-03-27 22:05
This doesn't seem to be working correctly with all of the html litter and red "Confirm...data method" messages in the last column of each table (screenshot below)

![super-admin](https://cloud.githubusercontent.com/assets/12703638/24380121/c020ed14-12fe-11e7-8a0c-ae04f95de229.png)

**Comment by vyruss** [comment] 2017-03-28 09:07
This looks like an en_US translation issue, @briri can you try copying `config/locales/administrate.en_GB.yml` to `config/locales/administrate.en_US` (editing the 2nd line to say en_US)?

**Comment by briri** [comment] 2017-03-28 15:23
The file does exist. It looks like passenger needed to be restarted. The translations appear to be working now.

**Comment by sjDCC** [comment] 2017-03-30 16:45
@stephaniesimms this all looks ok to me. Good for you now too?

**Comment by stephaniesimms** [comment] 2017-04-11 04:16
@sjDCC @vyruss I receive the errors below when I try to Edit or Destroy users. Everything else working as expected.

Edit user
![screen shot 2017-04-10 at 9 15 38 pm](https://cloud.githubusercontent.com/assets/12703638/24892625/e7d4e952-1e32-11e7-940a-a71d3bf57e54.png)

Destroy user
![screen shot 2017-04-10 at 9 12 05 pm](https://cloud.githubusercontent.com/assets/12703638/24892607/b919c272-1e32-11e7-9aa6-fe47d1012ee7.png)

**Comment by vyruss** [comment] 2017-04-11 10:47
@stephaniesimms deleting users is a **big no-no** due to data integrity issues so that's as expected. I'll look into the edit issue

**Comment by sjDCC** [comment] 2017-04-11 14:21
Perhaps we should remove the delete user button if this is a big no no? Or change it to 'archive' or 'deactivate' user. There's no point having something there that we don't want people to do.

I'm getting the same error with being able to edit users. I assume this page shows their permissions?

**Comment by stephaniesimms** [comment] 2017-04-11 15:17
@vyruss @sjDCC we definitely don't want to provide admins w/ability to delete users, per our discussion a couple of weeks ago. So we shouldn't present the expectation that they can—I agree that we need to remove the "Destroy" button. I agree w/the suggestion to remove "Destroy" under Organisations too.

**Comment by vyruss** [comment] 2017-04-13 15:52
1. Ability to `destroy` removed from super admin for now. A more sensible action will be implemented to disable users in the future.
2. Edit bug fixed.
3. @sjDCC can you please check on `dmponline-test` ?

**Comment by stephaniesimms** [comment] 2017-04-14 18:36
moving this back as it's not deployed to Roadmap server for UAT yet

**Comment by stephaniesimms** [comment] 2017-04-25 00:39
Edit user working as expected. Removal of Destroy option confirmed. Good to go. Closing out.

**Closed by stephaniesimms** 2017-04-25 00:39 UTC
Labels: admin, infrastructure, MVP
