### ISSUE TITLE
Consolidate DB migrations into one new migration

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#85] opened 2017-01-09 17:19 UTC
Remove all of the old DB migrations and build a new initial migration that is based on the current schema and any changes made to the DB from the onset of the Roadmap project to the end of the 1st week in January.

**Comment by briri** [comment] 2017-01-13 23:50
Started working on this but it makes sense to wait until after the DB refactor. Work was done in a branch on CDLUC3/roadmap

**Comment by briri** [comment] 2018-04-12 16:51
I still think we should do this just to clean up the migrations directory. A user cannot run `rake db:migrate` from a clean installation without encountering errors. It should be fairly easy to convert the the current schema.rb over to a migration file. @jollopre @vyruss and @xsrust what do you think?

**Comment by Yu-Chieh-Henry-Yang** [comment] 2018-08-03 03:57
I'm doing a project that use DMP Roadmap and we need to have database pass migration before going to production. Does anyone have an estimate about when the database consolidation this ticket mention will be finished?

Also, I provide a possible temporary workaround here: https://github.com/DMPRoadmap/roadmap/issues/1774 but I'm not sure if it breaks anything

**Comment by Bodacious** [comment] 2018-08-03 09:37
@briri @xsrust @Yu-Chieh-Henry-Yang This should not be necessary. The schema file (`db/schema.rb`) **_is_** a single migration that reflects the current DB structure. Creating a new, single migration would simply be a duplicate of the schema file.

The following rake tasks should be useful for almost all of the issues devs are likely to come across:

`rake db:migrate` should only be necessary when you have an existing DB that has fallen behind the schema at HEAD. If there are issues preventing those migrations from running, these should be added as issues with the **bug** label.

``` bash
rake db:reset          # Drop DB, create DB again, and load the schema to the current version
rake db:schema:load    # Load a schema.rb file into the database
rake db:create         # Creates the database from DATABASE_URL or config/database.yml for the current RAILS_ENV 
rake db:seed           # Load the seed data from db/seeds.rb (ONLY FOR DEVELOPMENT)
rake db:setup          # Create the database, load the schema, and initialize with the seed data (use db:reset to also drop the database first)
rake db:drop           # Drops the database from DATABASE_URL or config/database.yml for the current RAILS_ENV (use db:drop:all to drop all databases in the ...
rake db:migrate:status # Display status of migrations
rake db:rollback       # Rolls the schema back to the previous version (specify steps w/ STEP=n)
```

**Closed** 2018-08-03 15:43 UTC
Labels: database, effort-medium
