### ISSUE TITLE
Write Plan progress bar issue

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2573] opened 2020-06-23 22:09 UTC
The progress bar on the Write Plan page is off. Here is a snapshot of what it looks like when zero questions are answered. It should likely have no blue.
<img width="1164" alt="Screen Shot 2020-06-23 at 3 02 58 PM" src="https://user-images.githubusercontent.com/1204467/85469755-ec0e3d00-b562-11ea-9d74-21af1294aa8e.png">

The blue portion of the bar does not change until it goes beyond about 1/2 of the questions answered and then it works normally.

**Comment by xsrust** [comment] 2020-06-24 11:20
Looks like that's the behavior on our live services as well, so not caused by Rails5 changes

**Comment by raycarrick-ed** [comment] 2020-06-24 12:16
Fixed in: https://github.com/DMPRoadmap/roadmap/issues/2573

The text "x/y answered" was inside the progress bar which meant that it disappeared when the progressbar was set to 0. So a min-width had been set on the progressbar of 7em. Hence it appeared even when num answered was 0. Solution is to take the text out of the progressbar and into a floating div which sits on top of the progressbar and then the 2 are independent and can both show no bar for 0 while also saying "0/N answered".

**Comment by raycarrick-ed** [comment] 2020-06-25 08:50
This isn't rails 5. So we might want to pull this commit over early into the live systems if it's deemed important enough. It's a small fix.

**Comment by magdalenadrafiova** [comment] 2020-09-07 08:37
looks good - when the plan is started I saw zero: 
<img width="950" alt="Screenshot 2020-09-07 at 09 34 59" src="https://user-images.githubusercontent.com/47178106/92366855-97a04580-f0ed-11ea-9b3f-d27fabc43809.png">
& when I Started to answer questions I could see the number of questions I have answered (4 out of 13) 
<img width="963" alt="Screenshot 2020-09-07 at 09 35 20" src="https://user-images.githubusercontent.com/47178106/92366901-a850bb80-f0ed-11ea-812e-d7503bd34bc3.png">

**Closed by magdalenadrafiova** 2020-09-07 08:37 UTC
Labels: bug, rails5
