### ISSUE TITLE
404 error on public plan

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#734] opened 2017-10-17 11:03 UTC
One of my public plans is throwing an error on staging. Is this perhaps because 50% complete requirement has now been implemented and this doesn't need it?

![404](https://user-images.githubusercontent.com/6169940/31661573-25766c5a-b333-11e7-8767-48ee087cc550.PNG)

**Comment by sjDCC** [comment] 2017-10-17 11:35
I changed visibility on this plan and it now greys out the publishing options and has removed it from the list. i noticed Steph's "ethnography of gummi bears" throws the same 404. I guess what we're missing is a migration to remove any existing published plans that are less than 50% complete

**Comment by briri** [comment] 2017-10-17 15:25
Hey @sjDCC the new visibility restriction logic was just deployed this morning. It had been in PR previously. There is no limitation with regard to the 50% complete on the Public plans page. The logic was added to the share tab to prevent plans from ever being set to public unless they meet the criteria.

Here's the error. It looks like an issue with the linking of plans to co-owners:
![screen shot 2017-10-17 at 8 24 09 am](https://user-images.githubusercontent.com/1204467/31673651-a04e3c7e-b314-11e7-97f7-6b7238df37b6.png)

**Comment by stephaniesimms** [comment] 2017-10-22 14:27
public plans w/co-owners appear to be working as expected now. i can't reproduce this error. closing

**Closed by stephaniesimms** 2017-10-22 14:27 UTC
Labels: bug, MVP, plans
