### ISSUE TITLE
"My organization isn't listed." workflow is inconsistent

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1589] opened 2018-06-08 05:55 UTC
**Expected behaviour:**
I should not be able to edit the super admin in http://localhost:3000/super_admin/users/1/edit
OR
The "My organization isn't listed." button should work

**Actual behaviour:**
In http://localhost:3000/org/admin/users/admin_index, I can see the list of users, and there is no edit link under the privileges column. Then if I click that user who don't have the edit link button, I will arrive at http://localhost:3000/super_admin/users/1/edit.

But I shouldn't be able to edit it.

If I am able to edit it, the "My organization isn't listed." button doesn't work. (while the same button at http://localhost:3000/users/edit works)

**Steps to reproduce:**
1) Setup the roadmap application from scratch according to [installation wiki](https://github.com/DMPRoadmap/roadmap/wiki/Installation)
2) Open http://localhost:3000/org/admin/users/admin_index and click the first user (should be super user)
3) see that clicking the "My organization isn't listed."button doesn't work

**Note**
I tried to debug the issue by doing a system search on the key word "My organization isn't listed." but the js are all ulgified, do you have a normal version somewhere?

**Comment by xsrust** [comment] 2018-06-08 10:02
hi @Yu-Chieh-Henry-Yang,  thanks for the bug report. I can confirm that this is also an issue on our running services.

The view partial which renders that is shared with the edit profile page, and as is the js.

All of our js lives under `lib/assets/javascripts`
for whoever picks this ticket up, partial is `app/views/shared/_my_org.html.erb` and js at `lib/assets/javascripts/views/shared/my_org.js`

**Comment by briri** [comment] 2018-06-08 14:59
this may be fixed in #1588. If not we can add it since the PR makes modifications to those files for form validation updates.

**Comment by stephaniesimms** [comment] 2018-06-14 18:04
moving this to the current sprint so i can test. the link works now but the behavior should be the same as when a user clicks the "My Org isn't listed" link to edit their own profile or creates an account.

currently, as a Super Admin I get the following validation error if I don't enter a valid Org and then i can't save the changes (screenshot 1). I should be permitted to save this entry and/or provide a default "No affiliation" entry. 

this raises the question about how we're storing/identifying these free text user affiliations in the database. my understanding is that we want to present a "No affiliation" option and use this value in the db even if a user inputs something into this field. can someone confirm that this is the current db situation? our workflow for dmptool is slightly different so i'm confused about the correct behavior for roadmap.

![screen shot 2018-06-14 at 10 47 12 am](https://user-images.githubusercontent.com/12703638/41429354-c5a08b66-6fc1-11e8-973e-0edb1c15448d.png)

![screen shot 2018-06-14 at 10 53 24 am](https://user-images.githubusercontent.com/12703638/41429509-20cd0820-6fc2-11e8-877b-82d86da58fe8.png)

**Comment by stephaniesimms** [comment] 2018-06-15 23:13
this is working as expected now. closing issue,

**Closed by stephaniesimms** 2018-06-15 23:13 UTC
Labels: bug

**Comment by benjaminfaure** [comment] 2018-06-22 14:19
Hello,
You should probably add a rake to add a other_org in the database if there isn't at least one. 
It's not currently possible to add one through the UI. 

If there is no other orgs in the db, the form validation won't get through because the hidden field don't have a value, ex: 
`<input value="" name="user[other_org_id]" id="93_user_other_org_id" type="hidden"> `

**Comment by briri** [comment] 2018-06-22 14:21
that's a good point @benjaminfaure
