### ISSUE TITLE
Bullet points - strange formatting 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2147] opened 2019-05-30 11:34 UTC
When user downloads the plan - the bullet points appear to be strange, see image below. 
Would you be able to look into what have triggered this and find a fixture for this? 

![bullet-points](https://user-images.githubusercontent.com/47178106/58630339-067dd480-82d7-11e9-83e4-78f41ca91efe.png)

**Comment by johnpinto1** [comment] 2019-06-27 13:21
Unable to replicate on Live or Test servers. @magdalenadrafiova  is going to contact person who raised issue. It might be a specific template.
[Test_Funny_characters.docx](https://github.com/DMPRoadmap/roadmap/files/3334885/Test_Funny_characters.docx)
[Test_Funny_characters.pdf](https://github.com/DMPRoadmap/roadmap/files/3334886/Test_Funny_characters.pdf)

**Comment by magdalenadrafiova** [comment] 2019-07-03 10:00
We have other admins now having the same issue. 

They are using Chrome and the characters appear after they simply ‘download’ the template as Word and open it (no typing etc) 

Let me know if we need to know something more .

**Comment by johnpinto1** [comment] 2019-07-03 12:54
@magdalenadrafiova Is it possible to get a copy of the downloaded templates.

**Comment by magdalenadrafiova** [comment] 2019-07-03 15:06
![tudelft-formatting](https://user-images.githubusercontent.com/47178106/60602815-725acd80-9dac-11e9-8ed0-d0537e0b2a3d.jpg)

**Comment by briri** [comment] 2019-07-03 15:21
@johnpinto1 I would suggest looking at that particular plan's answer in the database to see if there is any odd formatting (e.g. maybe the user did a copy-paste from Word that had some extra HTML markup). 

I did a quick test in DMPTool and could not replicate the issue so I think it may be related to that specific template/plan.

**Comment by johnpinto1** [comment] 2019-07-03 15:33
@magdalenadrafiova and @briri  for that input. Will check.

**Comment by dsisu** [comment] 2019-07-04 08:56
Hi, the .pdf downloads correctly, the word doc has the funny characters. John is looking at it now.

**Comment by johnpinto1** [comment] 2019-07-04 09:05
The Word docx @dsisu provided is attached
[Some_TU_Delft_test.pdf](https://github.com/DMPRoadmap/roadmap/files/3358534/Some_TU_Delft_test.pdf)
[Some_TU_Delft_test.docx](https://github.com/DMPRoadmap/roadmap/files/3358535/Some_TU_Delft_test.docx)

I can read the Word **docx** correctly on a Linux machine, but the same **docx** in Windows replaces bullet points with &#8713; characters

**Comment by johnpinto1** [comment] 2019-07-04 11:19
@briri It looks like the database does not store the Bullet points (explicitly) Screen shot for data used by @dsisu in plan above in the ***question_options*** table:
![Selection_042](https://user-images.githubusercontent.com/8876215/60662939-b05ffc00-9e55-11e9-9e5a-88314ed24b75.png)

**Comment by dsisu** [comment] 2019-07-04 12:32
We will have to think what format we want to download the options as. So, people tick boxes to select some options, what do we want these to look like in the Word doc download? If we use symbols similar to bullet points, people will imagine this is a bulleted list and may expect to be able to edit it. However it's not possible; the download isn't a bulleted list but plain text with a a bullet-like symbol in front of it. If John fixes the file so that it downloads the text as a bulleted list, then Word inserts the funny symbol in front of it, possibly to highlight it's not a list but some kind of slection. I think this is why Word is struggling. We need to figure out what do we want the selected options to download as. Maybe we could have them as text with a couple of tick symbols in front of it, to indicate these were options selected (from a list of options). Hopefully this will make sense once I've inserted some screenshots.

**Comment by dsisu** [comment] 2019-07-04 12:36
![image](https://user-images.githubusercontent.com/2138956/60667152-b6a7a580-9e60-11e9-9310-9aca007f094c.png)

**Comment by dsisu** [comment] 2019-07-04 12:41
![image](https://user-images.githubusercontent.com/2138956/60667441-74329880-9e61-11e9-97ec-e6a6e3ea7bd2.png)

**Comment by dsisu** [comment] 2019-07-04 12:42
Sorry guys, I don't have time to format the images, please enlarge them to read my comments on the text.

**Comment by dsisu** [comment] 2019-07-04 12:43
What I mean by a tick symbol is something like this:
![image](https://user-images.githubusercontent.com/2138956/60667535-a47a3700-9e61-11e9-9fb6-2c19eaac4c64.png)

**Comment by dsisu** [comment] 2019-07-04 12:43
A tick symbol would hopefully remind users that what they are downloading is not a potentially editable bulleted list but a list of selections they made when they filled in the plan.

**Comment by dsisu** [comment] 2019-07-04 12:49
I'm going to send you the downloaded plans, which should hopefully help you work out what I mean, if the above isn't making sense.
[Test_download_incl_bulletedlist.docx](https://github.com/DMPRoadmap/roadmap/files/3359321/Test_download_incl_bulletedlist.docx)
[Test_download_incl_plaintextwithbulletsymbols.docx](https://github.com/DMPRoadmap/roadmap/files/3359322/Test_download_incl_plaintextwithbulletsymbols.docx)

**Comment by dsisu** [comment] 2019-07-04 12:51
I have to go now, I'll be able to respond to any queries later in the evening.

**Comment by johnpinto1** [comment] 2019-07-04 13:30
@briri I have identified the issue. The way the gem *htmltoword* package formats list in Word cases the issue. The relevant code *app/views/shared/export/_plan.erb*. 

![Selection_044](https://user-images.githubusercontent.com/8876215/60670291-384f0180-9e68-11e9-9c97-4e8ad83d7d76.png)


Unless I can't find a fix I guess we will need to have @sjDCC @magdalenadrafiova @xsrust and you @briri decide on @dsisu suggestion.

**Comment by benjaminfaure** [comment] 2019-09-27 13:20
We had this issue in DMP OPIDoR on our servers. I can confirm that this issue comes from the `<li>` tag being transformed as `€` sign in the Word export. 

We managed to bypass this by replacing our `<ul>` tag by a `<ol>` tag. 
It's not ideal but it works fine :)

Side note : the htmltoword doesn't seem to be able to export images in `<img>` in a Word document. It can be an issue in the future, we had some feedback from users asking to be able to export their org logo in their plan export.

**Comment by johnpinto1** [comment] 2019-10-04 10:46
Thanks @benjaminfaure for this comment.

**Comment by johnpinto1** [comment] 2019-10-04 14:54
@xsrust pionted me to this bug with htmltoword 
https://github.com/karnov/htmltoword/issues/73

**Comment by johnpinto1** [comment] 2019-10-04 15:00
@briri @xsrust There is still an issue with Older Word versions of software. Will see if I can fix it with suggestion from @xsrust's link above.

**Comment by briri** [comment] 2019-10-04 15:01
ok. send in a separate PR. thanks @johnpinto1

**Comment by johnpinto1** [comment] 2019-10-24 15:41
Fix for this is in review and @dsisu tested the following file 
[Test_Bullets_2 (8).docx](https://github.com/DMPRoadmap/roadmap/files/3768408/Test_Bullets_2.8.docx) using an old Word editor see screen shoot
![Selection_032](https://user-images.githubusercontent.com/8876215/67501977-1975b480-f67d-11e9-83e1-79b63fbf8160.png)

**Comment by sjDCC** [comment] 2019-11-05 15:12
tested this and bullets look good now. Thanks @johnpinto1 and @benjaminfaure for advice!

**Closed by sjDCC** 2019-11-05 15:12 UTC
Labels: bug, user
