### ISSUE TITLE
Create plan wizard

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#261] opened 2017-04-20 16:55 UTC
Is it feasible to add the other question from the UX wireframe to the create plan wizard now? 

I was surprised to only be asked a question about my funder, and expect we'll have confused UK users as naming your institution to get the local template is a key use case e.g. for PhD students. They way it's setup at present doesn't make it clear what will happen if you don't have a funder.

I would also prefer that you could pick guidance to include at this point too, even though you can switch it off later. It would make the optional guidance more prominent because it's very hidden otherwise. Many unis recommend that researchers select the DCC checkbox, so by removing it from this stage, we're requiring all their guidance be rewritten.

There's also no way to get the generic template now

![capture](https://cloud.githubusercontent.com/assets/6169940/25242541/ec3bee48-25f1-11e7-968d-3be01b3d28b1.PNG)

http://h90c3m.axshare.com/#g=1&p=create_plan

**Comment by briri** [comment] 2017-04-28 14:35
Same as #150

**Comment by briri** [comment] 2017-04-28 15:59
closing because this is a duplicate of #150

**Closed by briri** 2017-04-28 15:59 UTC
Labels: duplicate, MVP-v0.3, suggestion
