### ISSUE TITLE
Usage dashboard reports incorrect total plans

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1703] opened 2018-07-10 22:58 UTC
We noticed a discrepancy between total n plans as reported in the usage dashboard using the filters and total n plans when querying the dmptool database directly for many orgs, especially those with a lot of recent use. 

One possible contributor is the related bug issue #1663 . It looks like another contributor is that a single plan with multiple contributors/roles (owner, co-owner, editor, etc) is counted multiple times, one for each role. The correct calculation would count individual plan IDs per Org - so if plan A has an owner from UCOP and two co-owners from UCSF it should be counted once for UCOP and once for UCSF.

@sjDCC do we want to include test plans in total n? I'm okay either way but at least the total n on the dashboard should reflect the total n listed in the plans table. if we exclude test plans in the usage db we should just state that somewhere.

**Comment by sjDCC** [comment] 2018-07-11 12:19
Ideally the counts would list total plans and how many of those are marked as test. Can that be done?

**Comment by briri** [comment] 2018-07-11 16:08
No that's the query I used to get you counts that were close to the ones currently reported on usage dashboard. What we certainly want to do ensure is that:
- We understand which plans should be counted under which circumstances. Since plans are not directly related to orgs, we have to take the user(s) role into account (owner, coowner, editor, read-only)
- Test plans are those whose `plans.visibility == 2` and for non-test plans `plans.visibility != 2` so that should be fairly easy to break out for our statistics counts
- We also now have a `plans.completed` flag in the database so we could differentiate counts that way as well (note that its based on our squishy % of answers logic though)

The hardest part is with determine what to do based on the user's role and whether or not they've 'removed' the plan from their My Dashboard page (we never actually delete a plan, just the user's role. I think the answer to that is that "it depends" so we need to look at the different scenarios and figure out what to do for each one. 

@sjDCC and @stephaniesimms can you please go through these scenarios and define: A) which org(s) should include them on the Admin -> Plans list and B) which org(s) should include them in their usage statistics calculations?
- A plan has only one owner from DCC. 
- A plan has multiple owners and editors but they are all from DCC.
- A plan has one owner from DCC and was shared for read-only commenting with someone from UCOP
- A plan has one owner from DCC and was shared for editing with someone from UCOP.
- A plan has one owner from DCC and someone from UCOP was made a coowner.
- A plan was created by someone at DCC and shared with multiple people (from various orgs) but all users have since 'removed' it so that it no longer appears on anyone's My Dashboard page.
- A plan has an owner from DCC and a coowner from DCC. The coowner 'removed' it from their My Dashboard page.
- A plan has an owner from DCC and a coowner from DCC. The original owner 'removed' it from their My Dashboard page.
- A plan has an owner from DCC and a coowner from UCOP. The coowner 'removed' it from their My Dashboard page.
- A plan has an owner from DCC and a coowner from UCOP. The original owner 'removed' it from their My Dashboard page.
- A plan has an owner from DCC and a editor from DCC. The editor 'removed' it from their My Dashboard page.
- A plan has an owner from DCC and a editor from UCOP. The editor 'removed' it from their My Dashboard page.
- A plan has an owner from DCC and a editor from UCOP. The original owner 'removed' it from their My Dashboard page.
- A plan has an owner from DCC and a read-only commenter from DCC. The original owner 'removed' it from their My Dashboard page.
- A plan has an owner from DCC and a read-only commenter from UCOP. The original owner 'removed' it from their My Dashboard page.

So follow up questions:
- Does it matter if the user's account is inactive?
- Should test plans appear in the Admin -> Plans list?

**Comment by stephaniesimms** [comment] 2018-07-11 16:42
I replied to your scenarios and questions above @briri but @sjDCC should confirm and/or suggest any changes. I made the following assumptions:
- A plan should be counted in usage stats for an org if it has an affiliated owner or co-owner.
- A plan should NOT be counted for editor and read only roles.
- If all owners and co-owners have removed a plan it should not be counted in any usage stats but it may still appear on My Dashboard for editors and read only.
- If all users have removed a plan it should not be counted in usage stats or appear in the UI anywhere.
- If all users have deactivated/deleted their account, any associated plans should not be counted in usage stats or appear in the UI anywhere.
- Test plans should appear in the admin plans table and be counted in usage stats. If we can distinguish test plans in the UI w/future design changes, great. Otherwise the downloadable report should be sufficient to clarify how many of the total n are test plans.

**Comment by sjDCC** [comment] 2018-07-11 17:24
Yes, I agree with @stephaniesimms conclusions about when plans should show in stats and for which orgs. 

Plans should show up where the (co-)owner belongs to that org and hasn't removed the plan. This may result in plans appearing in multiple orgs statistics where there are co-owners from different places. Plans shouldn't appear in the admin list or usage stats for an editor or view / comment role though. And we should de-duplicate so the plan only appears once if there are several co-owners at the same org.

When users are deactivated, their plans should come out of the counts and views. The only way it would remain is if there was another active co-owner.

Test plans should appear in counts but it should be easy to identify how many are marked as test.

Nice, clear summary Steph

**Comment by xsrust** [comment] 2019-01-31 10:43
@sjDCC confirmed that the stats line up with the DB thismorning with Magdalena

**Closed** 2019-01-31 10:43 UTC
Labels: bug
