### ISSUE TITLE
Date picker question type option is not working

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1158] opened 2018-02-14 17:13 UTC
We have an option to pick a date as a question type but this is not working.

All seems well when you first select it
![first-edit](https://user-images.githubusercontent.com/6169940/36217843-5f2da7da-11aa-11e8-9094-13c8579a7227.PNG)

But different options are presented when you re-edit
![re-edit](https://user-images.githubusercontent.com/6169940/36217829-5ad77288-11aa-11e8-8aa6-db4e38a522d0.PNG)

And on the front end, nothing is displayed aside from the comments box. Not even the question text.
![how-question-displays](https://user-images.githubusercontent.com/6169940/36217850-63129d7e-11aa-11e8-9d7c-2eab4952cda9.PNG)

I think this was a code addition from Benjamin so it would be good to go back to that PR and see how it was supposed to work. it seems something has got mangled in interim and mixed up dates with multiple choice options and other styles which have the optional comments box.

**Comment by Yu-Chieh-Henry-Yang** [comment] 2018-06-14 04:21
Got this issue as well

**Comment by johnpinto1** [comment] 2019-02-13 16:05
@xsrust and @briri: In the development database dump the data in the **question_formats** table does not seem to have any *Date*

COPY question_formats (id, title, description, created_at, updated_at, option_based, formattype) FROM stdin;
1	Text area		2014-04-01 08:53:26	2014-04-01 08:53:26	f	0
2	Text field		2014-04-01 08:54:20	2017-06-23 08:42:12.232309	f	1
3	Radio buttons		2014-04-01 08:55:38	2017-06-23 08:42:12.235658	t	2
4	Check box		2014-04-01 08:56:45	2017-06-23 08:42:12.23837	t	3
5	Dropdown		2014-04-01 08:57:46	2017-06-23 08:42:12.240877	t	4
6	Multi select box		2014-04-01 08:59:24	2017-06-23 08:42:12.243513	t	5
7	RDA Metadata Standards	https://dmponline-test.dcc.ac.uk/rda/api/	2018-03-08 13:09:21.603416	2018-03-08 13:09:21.603416	f	7

I also noticed on https://dmponline-test.dcc.ac.uk you don't get a **Date** format in the list of **Answer formats**. 

Am I missing something here?

**Comment by briri** [comment] 2019-02-13 17:30
Hey @johnpinto1, the code behind this 'Date' question type was contributed by @benjaminfaure a while ago, in PR #92 but must have gotten lost during our recent refactoring efforts. 

You'll need to add the 'Date' question type value to your local DB as well as the `db/seeds.rb` and then a new rake task in `lib/tasks/upgrade.rb` that will add it to everyone's DB when they upgrade (see task `v2_1_9` in that file for an example ... which I think should be named `v2_1_1`, if you could do that rename as well that would be great ...  and name your new task `v2_1_2` to coincide with our next version number)

For the implementation I would just use the standard HTML5 `<input type="date">` field (in Rails it's `f.date_field :my_date_column`). That HTML5 field type doesn't provide a nice date picker in every browser though so you'll need to add a polypill as well to cover all scenarios. Here's an article that should be useful: https://code.tutsplus.com/tutorials/quick-tip-create-cross-browser-datepickers-in-minutes--net-20236

**Comment by briri** [comment] 2019-02-25 17:41
@johnpinto1 if you're interested, here is a link to the implementation we used on the Dryad project that you should be able to use for the UI portion of this ticket:
- [HTML5 date field](https://github.com/CDL-Dryad/stash/blob/01a93873a3ff84a3a692f53ccf20779b75b22970/stash_engine/app/views/stash_engine/admin_datasets/_curation_embargo_popup.html.erb#L9)
- [JS polypill](https://github.com/CDL-Dryad/stash/blob/master/stash_engine/app/assets/javascripts/stash_engine/date_picker.js)

This lets Chrome and Firefox use their native date pickers since they both support the HTML5 date field and then uses the jQuery-ui date picker for Safari (and I'm assuming IE) since they do not yet support it.

**Comment by johnpinto1** [comment] 2019-03-28 10:23
There is a separate issue raided for the Safari bug with the date picker #2075

**Comment by dsisu** [comment] 2019-04-03 10:49
I don't see a 'date' format for the questions. Sam confirmed this is not available. Keep this issue open, please.

**Comment by xsrust** [comment] 2019-04-03 11:54
I've added a date question format so this should work now

**Comment by dsisu** [comment] 2019-04-03 12:41
Works for me. Closing issue.

**Closed by dsisu** 2019-04-03 12:41 UTC
Labels: bug, effort-medium
