### ISSUE TITLE
Merge accounts

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2245] opened 2019-09-28 05:20 UTC
I spotted new functionality when testing the delete account feature #1489 I'm not sure we have a ticket for this so raising it here as it needs explanation and testing.
![new-feature](https://user-images.githubusercontent.com/6169940/65811885-4b4b4680-e1b7-11e9-9557-016dc3e50547.PNG)

Merge accounts allows you to take duplicate accounts and make them one. It seems you need to search for the primary user via the admin interface 'users' table and click to edit their profile.

As an aside, I think we need to change the table actions as the 'edit' button is actually editing privileges. to edit the user you need to click on the user name link. Perhaps we could have two actions "edit user" and "assign permissions" Thoughts @mariapraetzellis @magdalenadrafiova 
![accounts](https://user-images.githubusercontent.com/6169940/65811876-44243880-e1b7-11e9-9ad8-5794cc1249be.PNG)

Once you are editing the user, search for the duplicate account under the 'merge' box and click to merge. This copies plans over to the primary account. I tested this and my plans copied and I could no longer login with the old merged account. The user was no longer visible in the admin search table either.

A few questions on other implications @johnpinto1 @xsrust :
- What happens to any conflicting metadata e.g. PI name, ORCID or Shibboleth details. Does it keep the primary account values and only merge any empty field. Or no actions on metadata?
- What happens to any shared plans. Do users who shared plans with a merged account now see the new account affiliation. They should. I don't see any issues here as it will only be used to handle duplicates.
- Is the merged user removed from the stats?
- Who has access to this - admins or just super admins

**Comment by xsrust** [comment] 2019-09-30 14:06
@sjDCC I added the 'Merge' accounts while I was adding in the  'remove user' functionality.  
for DMPonline, we get many more  queries of the form 'I somehow ended up with two accounts, can you remove one and put it's plans on the other'  Than pure requests to remove an account.

Only super-admins can see this functionality, so I thought it was low-risk to include and figured it could evolve with our needs.  
Your understanding of how it works is correct.  After you find the account you want to keep, you can search for and select the account you want to  remove from that  interface on the right.

As for the logic, lets call the user we're keeping  Keep, and we'll call the user to be removed Remove.  All of Remove's plans are transfered to Keep.  All of Remove's answers/notes now belong to Keep.  if Keep did not previously have an ORCiD or Shibb login, and Remove does, Keep aquires the login details from Remove.  Remove is then deleted from the DB.

**Comment by mariapraetzellis** [comment] 2019-10-07 20:08
Since Sam confirmed this functionally is only for super-admins I'm not sure this is still relevant. However, responding to @sjDCC question regarding the table actions.... I agree that updated text would be useful. 

![screenshot-dmponline-test dcc ac uk-2019 10 07-12_45_55](https://user-images.githubusercontent.com/27511575/66343861-6168ad80-e901-11e9-809b-6bfc373f22e0.png)

Also the text explaining which account is being merged into which is still a bit confusing. The text currently reads: "The selected user's content will be merged into this account. The selected account will then be removed."  

I think specifying which account is being merged into which would be helpful. Maybe something like:
'The account for maria.praetzellis@ucop.edu will be merged with maria@ucop.edu. All plans and account information for maria@ucop.edu will now be accessible via maria.praetzellis@ucop.edu'  
Thoughts @sjDCC @magdalenadrafiova?

**Comment by sjDCC** [comment] 2019-10-09 16:43
Thanks @mariapraetzellis 

I agree with new wording for account merge. Defo helpful to specify which email is being merged into which.

For table, I wonder if we should rename final column to 'Actions' akin to templates table and have two dropdown options. "Edit user" and "Assign privileges" That would keep the interface consistent and hopefully more intuitive.
![Picture1](https://user-images.githubusercontent.com/6169940/66501929-3f675a80-eabc-11e9-8f59-d579f7e8088a.png)

**Comment by sjDCC** [comment] 2019-11-05 15:22
Functionality works well but we still need to update message text. Please see @mariapraetzellis wording:
'The account for maria.praetzellis@ucop.edu will be merged with maria@ucop.edu. All plans and account information for maria@ucop.edu will now belong to maria.praetzellis@ucop.edu'

![Capture](https://user-images.githubusercontent.com/6169940/68220669-0e594780-ffe0-11e9-9c75-9c30d154dbb5.PNG)

**Comment by magdalenadrafiova** [comment] 2019-11-05 16:25
Looks good - just as Sarah and Maria mentions above needs to say the first part which account will belong to which.

**Comment by mariapraetzellis** [comment] 2019-11-26 16:41
@xsrust to review and finish up Wednesday 11/27.

**Comment by magdalenadrafiova** [comment] 2019-11-29 14:12
The text appears correctly: 
![image](https://user-images.githubusercontent.com/47178106/69874116-1a1fed00-12b2-11ea-8ccd-14f91c86f2e5.png) & after I merged accounts I could also see additional plans being added to the account. works well closing this

**Closed by magdalenadrafiova** 2019-11-29 14:12 UTC
Labels: admin, orgs
