### ISSUE TITLE
Expand/contract symbols (+/-) not displaying correctly

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#1298] opened 2018-03-15 17:11 UTC
Please complete the following fields as applicable:

**Expected behaviour:**

Section should expand when user clicks +
Section should contract when user clicks -

**Actual behaviour:**
- Section doen't always expand when user clicks +, but the button turns to - . In other words, it sometimes takes two clicks to expand a section. When the section finally expands, the button turns to +. See two screenshots enclosed below.

![image](https://user-images.githubusercontent.com/2138956/37478119-5201d954-2871-11e8-8d66-82316e365682.png)

![image](https://user-images.githubusercontent.com/2138956/37478210-872bf93e-2871-11e8-8b32-7623f4aea7c9.png)

**Steps to reproduce:**

Create plan go to Edit (or Edit any existing plan) and try to expand contract sections. ZonMw template reproduces the error. Horizon2020 does it one and off.

**Comment by briri** [comment] 2018-03-15 18:51
yes @vyruss that seems to be the case. If you wait for the page to finish loading its not an issue. As you note, its tied to the way the page loads everything all at once instead of when the individual accordion sections are expanded.

**Comment by dsisu** [comment] 2018-03-15 20:28
For the record, another user who mentioned this was for DMP template of Hanze University of Applied Sciences.

**Comment by dsisu** [comment] 2018-03-15 20:31
@briri It's one of those things, you're not even aware the page is still loading so you click on the plus again, thinking that maybe you haven't 'hit the button'. Not a major issue but worth fixing. Thanks!

**Comment by sjDCC** [comment] 2019-09-30 19:59
Working now. Closing out.

**Comment by xsrust** [comment] 2019-10-01 08:57
I don't think that this was worked on,
I can reproduce this on -test.
You just need to expand an accordian before the page loads in all the way
![Screenshot 2019-10-01 at 09 56 48](https://user-images.githubusercontent.com/7352616/65948259-d0419480-e431-11e9-8a6c-73eb2b20abb9.png)

**Closed** 2021-04-26 15:35 UTC
Labels: bug
