### ISSUE TITLE
create/update/destroy annotations actions should not belong to questions_controller 

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#1462] opened 2018-05-08 14:44 UTC
**Expected behaviour:**

- views/org_admin/questions/_edit.html.erb should include two partials new/edit for guidance and example_answer respectively.
- views/org_admin/questions/_show.html.erb should include two partials new/edit for annotations instead of handling both type of annotations together
- controllers/org_admin/questions_controller.rb should not have the logic to create/update/destroy annotations there

**Actual behaviour:**
When we add/modify a new question through questions_controller, currently the logic regarding the annotation actions (create/update/destroy) is hardcoded there.

**Comment by briri** [comment] 2018-05-16 15:40
The question partials do generate separate partials for each of the 2 annotation types. The calls to display those partials are found within the views/org_admin/questions/_form.html.erb and _show.html.erb files:
```ruby 
  <%# example_answer and guidance annotations as nested fields %>
  <% question.annotations_per_org(current_user.org_id).each do |annotation| %>
    <%= f.fields_for(:annotations, annotation) do |annotation_fields| %>
      <%= render partial: 'org_admin/annotations/form', locals: { f: annotation_fields } %>
    <% end %>
  <% end %>
```

Unless we're going to implement auto-save for the entire page I don't see the benefit of having separate controller endpoints to handle annotation CRUD operations. We do this for question_options as well so whatever approach we take should be the same for both since they are both associations of the question. I suppose you could say that in make sense when it comes to annotations since the user is only updating annotations at that point (unless its a custom section of course) but why not just reuse the existing logic to handle the save (through the question) instead of implementing and maintaining duplicate sets of code?

**Comment by stephaniesimms** [comment] 2018-05-16 17:03
@sjDCC and I have confirmed that annotations are working well now w/one minor bug reported. and we do have an issue to implement auto save throughout the site #1160. considering how much time you've already spent on template work I think it's in great shape for now. maybe we can assess further refinements when we get to autosave?

**Comment by stephaniesimms** [comment] 2018-05-21 16:30
cleaning up the board and closing this issue since it's no longer relevant

**Closed by stephaniesimms** 2018-05-21 16:30 UTC
Labels: effort-medium
