### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#258] opened 2017-04-20 13:40 UTC
Error message needs updating when email is not known by system

![wrong-email](https://cloud.githubusercontent.com/assets/6169940/25233599/3e0cc2a8-25d7-11e7-9dea-9502bdf95413.PNG)

**Comment by jollopre** [comment] 2017-04-21 13:59
The error prompted comes from devise gem. This gem, still runs with I18n and the .yml files are loaded at https://github.com/DigitalCurationCentre/roadmap/blob/development/config/initializers/locale.rb#L2. 
Inspecting the devise .yml files located at config/locales/device, I don't find the entry invalid at any of these files, however I'm not able to reproduce this error. 

@sjDCC if you remember the steps that lead to this error, please let me know.

**Comment by sjDCC** [comment] 2017-04-21 15:29
I've just tried to recreate this on staging and can't so it was perhaps a random quirk. 

I'm now just getting the usual invalid email error message

**Comment by stephaniesimms** [comment] 2017-04-24 23:39
I get the expected invalid email error message. Closing out.

**Closed by stephaniesimms** 2017-04-24 23:39 UTC
Labels: bug, MVP-v0.3
