### ISSUE TITLE
Replacing Attr_accessible with permitted params

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#215] opened 2017-03-30 15:49 UTC
In rails 4, the old `attr_accessible` syntax became depricated and it's functionality replaced with [Strong Parameters](https://github.com/rails/strong_parameters/).  
This functionality is allowed in our application by the gem [protected_attributes](https://github.com/rails/protected_attributes), which will stop being supported as of rails 5.

In preparation for this, we should remove the `attr_accessible` from the models, and add strong parameters to any controllers which do an `record.update_attributes(params)`.

**Comment by briri** [comment] 2018-04-12 17:34
duplicate of #100

**Closed by briri** 2018-04-12 17:34 UTC
Labels: infrastructure
