### ISSUE TITLE
uninitialized constant Template::TemplateScope

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1658] opened 2018-07-05 00:36 UTC
**Expected behaviour:**
When starting up the rails server with `rails s -d`, and access it via browser, it should work

**Actual behaviour:**
It show me this page instead
![screen shot 2018-07-05 at 10 05 43 am](https://user-images.githubusercontent.com/19463606/42297018-07b9eb12-803b-11e8-9f04-45217e028fe4.png)

**Steps to reproduce:**
install the app normally and use rails s -d to start the application.

**Comment by Yu-Chieh-Henry-Yang** [comment] 2018-07-05 01:54
In config/environments/development.rb, if I do 
`config.cache_classes = true`
then it solves my problem, but I don't know why it doesn't load, perhaps when I use `config.cache_classes = false` it is not loaded in any request at all? 

Rails website says:
> config.cache_classes controls whether or not application classes and modules should be reloaded on each request. Defaults to false in development mode, and true in test and production modes.

**Comment by Bodacious** [comment] 2018-07-11 08:49
Hi @Yu-Chieh-Henry-Yang 

This seems like a problem with the load sequence. Rails will autoload files from the models directory, and it appears that `app/models/template.rb` is being loaded before `app/models/scopes/template.rb`.

This shouldn't happen, even with `cache_classes = false` (which is the desired setting for dev).

Can you tell me more about your development environment? I'm not able to reproduce this on my own local development machine.

Would you mind trying the following:

- Move the file `app/models/scopes/template_scope.rb` into `app/models/concerns/template_scope.rb`
- Restart your Rails server

 I think Rails might be missing the file in the `scopes` directory because there's no `Scopes` module prepended to the name. The Rails naming convention is for class names to match their directory structure.

**Comment by Bodacious** [comment] 2018-07-11 10:19
Update: I've just encountered this issue myself. Submitting a quick PR to fix.

**Comment by briri** [comment] 2018-07-12 17:41
No UAT needed for this one so closing out

**Closed by briri** 2018-07-12 17:41 UTC
