### ISSUE TITLE
Optimistic locking occasionally conflicts with auto-save on structured questions

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2515] opened 2020-05-15 15:36 UTC
When users are answering structured questions, the autosave sometimes occurs at the same time they hit the save button manually. This is more likely that in text editing. It can give a confusing message, see below:
![Delft](https://user-images.githubusercontent.com/6169940/82068605-1e0dc300-96ca-11ea-8c03-2ef2a07b4170.jpg)

How should we resolve it? Remove autosave from radio/checkboxes or write in logic to ignore if user is the same?

**Comment by sjDCC** [comment] 2020-05-20 10:08
This is linked to #2520 Address the two together

**Comment by pherterich** [comment] 2020-06-25 16:08
Closing as duplicate of #2520

**Closed by pherterich** 2020-06-25 16:08 UTC
Labels: usability
