### ISSUE TITLE
Upgrade to Rails 5.2

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#114] opened 2017-02-28 15:00 UTC
This might be a low-priority issue worth looking at after MVP just to avoid obsolescence.
[Upgrading from Rails 4.2 to Rails 5.0](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0)

**Comment by mxsstrong** [comment] 2017-02-28 17:15
suggested by @paulwalk to wait for stable release of Rails

**Comment by briri** [comment] 2018-04-12 17:02
duplicate of #826

**Closed by briri** 2018-04-12 17:02 UTC
Labels: infrastructure, suggestion
