### ISSUE TITLE
Fix email formatting when invited to edit a plan

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#239] opened 2017-04-11 22:19 UTC
The notification email needs a space and open quotes before the plan name (screenshot below)

![screen shot 2017-04-11 at 3 15 50 pm](https://cloud.githubusercontent.com/assets/12703638/24933203/f58eec04-1ec9-11e7-88f9-9db3681e9bb2.png)

**Comment by sjDCC** [comment] 2017-04-13 10:03
Also, what name is stated? If we have an actual name in the system rather than just an email address it would be better to default to that.

**Comment by xsrust** [comment] 2017-04-13 14:01
fixed in https://github.com/DigitalCurationCentre/roadmap/commit/d30bdc4021aaf456819ca8897174c7cfcde381b6   and https://github.com/DigitalCurationCentre/roadmap/commit/3e5c12ef1d2e14442a03fee7bc54c6136be0d3e9

Since my local machine dosent send out emails, I would leave the confirmation that the display is as intended to the next time the code is deployed to a staging server.

Additionally, the changes suggested by @sjDCC are trivial to implement so it might make sense to update the email notifications for change of permissions and for revoking permissions to read similarly

**Comment by sjDCC** [comment] 2017-04-13 14:07
If someone can give me and @stephaniesimms the text for any automated email notifications we can suggest text changes. Have a feeling some are a bit brief and come across like spam :)

**Comment by briri** [comment] 2017-04-14 20:34
Here's the automated email texts:
```
Hello someone@tester.org

Your permissions relating to "My plan (Horizon 2020 DMP)" have changed. You now have co-owner access.
```
the title above is a link in the email
```
Hello someone@tester.org!

A colleague has invited you to contribute to their Data Management Plan at DMPRoadmap

Click here to accept the invitation, (or copy http://roadmap-stg.cdlib.org/users?invitation=ABCDEG into your browser)

If you don't want to accept the invitation, please ignore this email.
Your account won't be created until you access the link above and set your password.
```
DMPRoadmap and the 'Click here' portion are links in the email
```
Hello someone@tester.org

You have been granted permission by your organisation to use our API. Your API token and instructions for using the API endpoints can be found here.
```
The 'Your API token' sentence is a link in the actual email
```
Hello someone@tester.org

Your access to "My Plan" has been removed.
```
The title is a link in the email
```
Welcome to DMPRoadmap, someone@tester.org!

Thank you for registering. Please confirm your email address:

Click here to confirm your account, (or copy http://roadmap-stg.cdlib.org/users?confirm=ABCDEG into your browser)
```
The DMPRoadmap and 'Click here' section are links in the email

**Comment by sjDCC** [comment] 2017-04-18 10:31
@stephaniesimms I've added these texts to a googledoc so we can agree edits. See: https://docs.google.com/document/d/1Zt3QfPZ2q6yMOCVFOevXviwRX-XbZeGSxAAvbRa9w-M/edit?usp=sharing

**Comment by stephaniesimms** [comment] 2017-04-19 17:38
WELCOME EMAIL
```
Email title: Welcome to [TOOL NAME]   

Welcome to [TOOL NAME], someone@tester.org!   

[TOOL NAME] will help you to develop your Data Management Plan. If you have any queries or feedback as you use the tool, please contact us on [INSERT HELPDESK EMAIL]   

All the best,   
The [TOOL NAME] team
```
CHANGED PASSWORD
Email title: Password change on [TOOL NAME]
Hello someone@tester.org

Someone has requested a link to change your [TOOL NAME] password. You can do this through the link below.

Change my password

If you didn't request this, please ignore this email.
Many thanks
The [TOOL NAME] team

SHARED PLAN
Email title: A Data Management Plan in [TOOL NAME] has been shared with you
Hello someone@tester.org

A colleague has invited you to contribute to their Data Management Plan at [TOOL NAME]

Click here to accept the invitation, (or copy http://roadmap-stg.cdlib.org/users?invitation=ABCDEG into your browser)

If you don't want to accept the invitation, please ignore this email.


All the best
The [TOOL NAME] team

AMENDED PERMISSIONS ON A PLAN
Email title: Changed permissions on a DMP in [TOOL NAME]
Hello someone@tester.org

Your permissions relating to "My plan (Horizon 2020 DMP)" have changed. You now have co-owner access. This means you can write and edit the plan in a collaborative manner. You can also grant rights to other collaborators.
All the best
The [TOOL NAME] team

Hello someone@tester.org

Your permissions relating to "My plan (Horizon 2020 DMP)" have changed. You now have editor access. This means you can write and edit the plan in a collaborative manner. 
All the best
The [TOOL NAME] team

Hello someone@tester.org

Your permissions relating to "My plan (Horizon 2020 DMP)" have changed. You now have read-only access. This means you can read the plan and leave comments. 
All the best
The [TOOL NAME] team

Email title: Permissions removed on a DMP in [TOOL NAME]
Hello someone@tester.org

Your access to "My Plan" has been removed by [INSERT USER NAME].
All the best
The [TOOL NAME] team

API RIGHTS
Email title: API rights in [TOOL NAME]
Hello someone@tester.org

You have been granted permission by your organisation to use our API. Your API token and instructions for using the API endpoints can be found here.
All the best
The [TOOL NAME] team

**Comment by stephaniesimms** [comment] 2017-04-19 17:45
@briri new email text is pasted above. also available in the Google doc linked above that. let me know if you have questions.

**Comment by stephaniesimms** [comment] 2017-05-01 17:49
So far tested functions all sent expected emails...Closing issue

**Comment by stephaniesimms** [comment] 2017-05-01 18:01
@briri 'Amended Permissions on a Plan' emails (n = 4) are incomplete. They should include the full text as it appears above and in the Google doc. At present, they look like this:

Hello stephanie.simms@gmail.com

Your permissions relating to "Notifications test plan (AMK)" have changed. This means you can read the plan and leave comments.

All the best, 
The DMPRoadmap - STAGE team.

**Comment by sjDCC** [comment] 2017-05-12 16:09
This doesn't appear to be fixed. Could you check too @stephaniesimms 

The issue was to amend the text in the message when sharing a plan, but this appears more garbled than before now... 
![garbled-message](https://cloud.githubusercontent.com/assets/6169940/26006680/41b8d88c-3735-11e7-833a-018e2592bd6e.PNG)

I also encountered another error. If I share a plan with an email for which there is not an account, I am not alerted to this. This email came out:
![capture](https://cloud.githubusercontent.com/assets/6169940/26006738/7b9795f2-3735-11e7-9553-4f0cf030cc4e.PNG)

But then when I tried to login I got an error as the invited email is unknown
![error2](https://cloud.githubusercontent.com/assets/6169940/26006757/8cd42f4c-3735-11e7-824a-e37066776ba3.PNG)

@vyruss is this issue covered by #307 Will that fix involve updating the text and links in this email notification?

I also hit a problem with this on DMPonline-test in that the links in our auto email are to an old dead server. These need to be updated
![dmponline-test](https://cloud.githubusercontent.com/assets/6169940/26006820/cc5666c6-3735-11e7-8430-bbf05f5ab631.PNG)

**Comment by sjDCC** [comment] 2017-05-12 16:15
For clarity, the current errors in the email out to someone who a plan has been shared with are highlighted in bold below.

Your permissions relating to "My plan (AHRC Template)" **have been changed by** Sarah Jones. You now have editor access. **to** This means you can write and edit the plan in a collaborative manner.

**Comment by vyruss** [comment] 2017-05-15 21:09
@sjDCC specifically in the non-user invitation email, it is intentional that we don't give out the name of the plan creator and the plan, as the invitee is not a registered user and the email address may be wrong. It has always been like that and a change will need rewriting this code. 

The "have been changed" issue was a rogue fuzzy translation which is now fixed.

**Comment by sjDCC** [comment] 2017-05-16 13:36
Tested on DMPonline-test and message texts are all accurate now for sharing plans and changing permissions. Closing this out.

@vyruss, regarding the non-user invitation, I would have thought sharing the plan creator name would have helped lend some credibility to this invite and avoid the email looking like spam. Happy for it to be left as is though if not including it was intentional.

**Closed by sjDCC** 2017-05-16 13:36 UTC
Labels: bug, MVP-v0.3
