### ISSUE TITLE
Org visibility plan will appear in the public DMPs only if filled 100%

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#3086] opened 2022-01-11 09:44 UTC
Currently when the researcher wants to make their plans visible, it says in the description that it has to be filled at least 50%, however, it is not true as a plan will not appear unless it is 100% filled. 
Could we change this back to 50% percent of the plan has to be filled as appears in the text for the researchers? 

@briri @raycarrick

**Comment by nicolasfranck** [comment] 2022-04-20 13:44
The problem is also: 50% of what? There can be multiple phases..

**Comment by johnpinto1** [comment] 2022-05-10 11:21
The fix in PR https://github.com/DMPRoadmap/roadmap/pull/3172

**Comment by pherterich** [comment] 2022-05-20 09:35
Closing here as this is now included in release 3.1.1

**Closed by pherterich** 2022-05-20 09:35 UTC
Labels: plans, create plan
