### ISSUE TITLE
Guidance group options differ on Tuuli test and live

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#400] opened 2017-06-06 10:37 UTC
Different guidance group options are presented between test and live Tuuli. I created a plan for Tekes on live and got the following options. Finnish DMP guidance is their main generic DMP guidance, akin to DCC guidance.
![tuuli-options-live](https://cloud.githubusercontent.com/assets/6169940/26825251/35d367d2-4aac-11e7-9c04-7c5ae79a15ad.PNG)

When re-creating this on test, different options appear. Finnish DMP guidance is absent (along with others) but there is definitely guidance available on this template (see later screengrab) so it's not been filtered out for a reason. The label for 'other institutional guidance' is also missing
![tuuli-options-test](https://cloud.githubusercontent.com/assets/6169940/26825301/68379ed2-4aac-11e7-882d-e03f3efb89ea.PNG)
![tekes-live](https://cloud.githubusercontent.com/assets/6169940/26825320/7a84907c-4aac-11e7-82e1-d165f848e584.PNG)

**Comment by sjDCC** [comment] 2017-06-06 10:40
I've just realised that it might not be missing guidance group, just that the display names are different...

DCC (UK) guidance > Digital Curation Centre
Finnish DMP guidance > Tuuli
FSD... > Finnish Social Science Data Archive

Are we pulling a different field e.g. org name rather than guidance group name?

It would be best to draw the same so it's less change for users and more intuitive

**Comment by vyruss** [comment] 2017-06-06 11:01
Because of the very poor main guidance names ("Uni guidance", blank, etc) we had in dmponline, the guidance selection has been rewritten to show the institution name instead of the main guidance name. I believe we should keep it this way as the code should not diverge between Tuuli and DMPonline.

**Comment by sjDCC** [comment] 2017-06-06 17:17
Ok, let's leave it as it stands and see what comes out of Finnish testing. Should we close out for now?

**Comment by vyruss** [comment] 2017-06-06 18:46
It's intended behaviour so I'd lean towards closing

**Closed** 2017-06-07 11:21 UTC
Labels: DMPTuuli, guidance
