### ISSUE TITLE
Rails 6 

### ISSUE THREAD

**Issue by benjaminfaure** [DMPRoadmap/roadmap#3103] opened 2022-02-03 11:10 UTC
Hello everyone,

According to Rails maintenance policy, Rails 5.2 we'll reach its end of life in June 2022
https://guides.rubyonrails.org/maintenance_policy.html

Seems like yet another Rails upgrade is on the horizon.

Rails 7 is already out, I guess they switched to yearly release for major versions of the framework. Hopefully upgrading won't be such a big step anymore

**Comment by briri** [comment] 2022-02-23 16:46
Just discovered today that Rails is [no longer supporting the Webpacker gem](https://github.com/rails/webpacker). I learned this after running `yarn upgrade` and noticing that all of the Karma tests would no longer run due to a mismatch in dependencies for webpack.

Rails 7 moves away from Webpacker and provides [3 new options for how to manage JS](https://world.hey.com/dhh/rails-7-will-have-three-great-answers-to-javascript-in-2021-8d68191b)

We should also consider upgrading:
- Bootstrap (we are 2 major versions behind) - this will require significant work
- TinyMCE - we tried upgrading but the editors stopped loading
- JQuery - we might want to consider moving away from JQuery and just using vanilla JS (depending on how much work will be involved to upgrade)

**Comment by benjaminfaure** [comment] 2022-05-06 14:13
I took some time and tried to upgrade the roadmap code to Rails 6.1.

It went fairly well. I tested some of the feature and with some minor corrections I managed to get the roadmap code to run.
I'm not sure how we could start to share the work done on the migration. Should we create a new branch and commit it ?

**Comment by pherterich** [comment] 2022-05-16 10:16
Tagging @gjacob24 here as she wanted to give this an initial look for the DMPonline team

**Comment by briri** [comment] 2022-06-03 15:31
Added a new wiki page to record upgrade notes: https://github.com/DMPRoadmap/roadmap/wiki/Rails-Upgrade-Notes

The intended audience would be developers who manage their own instances and may need to upgrade their own cutomizations

**Comment by briri** [comment] 2022-06-06 14:47
I was just doing some reading on Rails 7 and discovered that they're moving away from Webpacker and UJS (which they introduced in Rails 5/6). An apparent side effect is that there is no longer support for `js.erb` (would have been nice if they deprecated instead and made this backwards compatible). 

This is going to have a potentially significant impact on us: https://guides.rubyonrails.org/working_with_javascript_in_rails.html

**Comment by pengyin-shan** [comment] 2022-06-06 15:01
> I was just doing some reading on Rails 7 and discovered that they're moving away from Webpacker and UJS (which they introduced in Rails 5/6). An apparent side effect is that there is no longer support for `js.erb` (would have been nice if they deprecated instead and made this backwards compatible).
> 
> This is going to have a potentially significant impact on us: https://guides.rubyonrails.org/working_with_javascript_in_rails.html

Yes, we also tried to remove webpacker in another project after the Rails upgrade. Just an FYI that the Rails conference is next week (June 15), they might introduce Rails 6/7 features and how to upgrade (mainly Rails 7 I think). I will update here if I find anything helpful for us.

**Comment by briri** [comment] 2022-06-06 15:06
Thanks @pengyin-shan!

I find it super frustrating that they would not make something like that backwards compatible since they introduced it and guided us all to adopt it :/

**Comment by pengyin-shan** [comment] 2022-06-06 15:12
> Thanks @pengyin-shan!
> 
> I find it super frustrating that they would not make something like that backwards compatible since they introduced it and guided us all to adopt it :/

I personally feel that handling javascript is the 'special' (?) part of the Rails framework, compared to other frameworks because the MVC style is more strictly maintained in Rails. Now since other frameworks are becoming more flexible in interacting with js (like node, which is easy to add front-end framework like react or angular), Rails team is also trying to catch the trend. But this is a periodical pain because now the framework needs to balance between strict MVC rules and client-side interactions.

**Comment by pengyin-shan** [comment] 2022-06-06 15:17
> I was just doing some reading on Rails 7 and discovered that they're moving away from Webpacker and UJS (which they introduced in Rails 5/6). An apparent side effect is that there is no longer support for `js.erb` (would have been nice if they deprecated instead and made this backwards compatible).
> 
> This is going to have a potentially significant impact on us: https://guides.rubyonrails.org/working_with_javascript_in_rails.html

As for `js.erb`, I wonder if it is better for us to start split now (i.e. start to use js in Rails 6) that next year we need to do this again?

**Comment by briri** [comment] 2022-06-06 15:23
Agreed, the boundaries between the two have always been a bit strange and hard to manage. There doesn't appear to any official guidance at this point. for example: https://stackoverflow.com/questions/71422105/rails-ajax-rails-is-not-defined-rails-7

This likely means that we cannot move to 7 this summer and will need to deal with it next year. I wonder if its a good opportunity to start moving towards a JS framework like React or Vue. Some of my colleagues have done this in their Rails projects and they've been able to manage it without having to rewrite the entire application (e.g. they have a single page that is managed with React).

We moved to the js.erb model because most of our individual strengths have been with backend development and Rails. The JS skillset is something we would need training on. Do any of the @DMPRoadmap/devs have experience with React or another JS framework?

@pengyin-shan if you could find out what their official recommendations are at the conference, that would be great!

**Comment by pengyin-shan** [comment] 2022-06-06 15:34
@briri  for sure I will pay attention to this!

For the adding front-end framework thing, I was recently trying to add react to node (I think a similar way could work for Angular or Vue, not sure about Rails side though). 

A possible pattern is that the server-side deals with API only. 

For example: 
```
app.get("/api", (req, res) => {
  res.json({ message: "API ready for get request" });
});
```

And the client side proxy to the server:

```
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "proxy": "http://localhost:3001"
```

But I haven't tried rails yet...we need to change a lot using this way. So probably a simple re-write of `js.erb` is better for now?

**Comment by gjacob24** [comment] 2022-06-13 16:03
Created a new issue [#3187](https://github.com/DMPRoadmap/roadmap/issues/3187) to keep a track of all the tasks needed to be completed before the rails 6 release. Hope it's useful. I will add tasks to it as I do some user testing. Please edit as required.

**Comment by StCyr** [comment] 2022-08-05 08:23
It's a mess here on Ubuntu 22.04

I could not install ruby 2.7 because of an SSL issue (openssl dropped support for an encryption scheme needed to compile ruby 2.7).
So I went for ruby 3.
This makes me stumble on an issue when running `rails credentials:edit`. Apparently the cause is that rails 5.2 isn't compatible with ruby 2.7.
So I've tried to upgrade to rails 6.1 but roadmap depends on `devise_invitable` whose latest version depends on `actionmailer´ 5 while rails 6.1  requires actionmailer 6.1

It looks like I'm on a dead-end street; The only solution left for me seems to downgrade openssl on my server... bad :disappointed:

**Closed** 2022-11-28 21:15 UTC
Labels: infrastructure, effort-large, need-to-slice, Epic, rails6
