### ISSUE TITLE
Display total Org users, total plans in the UI

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1760] opened 2018-07-26 18:39 UTC
- Admins would like to see at a glance how many users or plans they have without downloading a report
- Proposal to display these data in a similar manner as we do on the homepage for global stats (screenshots below from DMPTool and DMPonline), but for a specific Org

DMPTool homepage
![screen shot 2018-07-26 at 11 17 32 am](https://user-images.githubusercontent.com/12703638/43281386-6101c90e-90c8-11e8-86e8-20d6038df137.png)

DMPonline homepage
![screen shot 2018-07-26 at 11 18 24 am](https://user-images.githubusercontent.com/12703638/43281389-630153e6-90c8-11e8-81eb-72d058b0d870.png)

**Comment by johnpinto1** [comment] 2018-09-05 12:59
@stephaniesimms  & @sjDCC  On what page do you want the stats to appear?

**Comment by stephaniesimms** [comment] 2018-09-12 16:27
- I agree w/ @sjDCC that the labels should say "603 Total users" and "749 Total plans"
- For alignment, I would move the icons to the left (first preference) or center them (second preference). Currently they seem to be floating somewhere left of center.
- It's fine to remove the name of the university. We can evaluate the overall page and context once this is deployed to make sure it's clear to users that these are Org stats and not global stats. Currently, there's a branding banner above and the line of text below for the filters, neither of which makes it crystal clear that these are Org totals. But the rest of the page will change as Jose continues work so I think we can wait on it for now.

thanks @johnpinto1 !

**Comment by johnpinto1** [comment] 2018-09-14 15:11
@stephaniesimms I think I have incorporated your suggestions here:
![usage-totals](https://user-images.githubusercontent.com/8876215/45558888-e4bbea80-b838-11e8-8966-117a090ba53e.jpeg)

**Comment by johnpinto1** [comment] 2018-09-14 15:33
@stephaniesimms Updated as suggested. I will push code for review if this is acceptable.
![usage-totals](https://user-images.githubusercontent.com/8876215/45559960-c4d9f600-b83b-11e8-8204-c4f1b28b7045.jpeg)

**Comment by stephaniesimms** [comment] 2018-09-14 16:02
screenshot looks good to me @johnpinto1 - cheers. i moved the issue to the current sprint board so we can track it.

**Comment by sjDCC** [comment] 2018-10-05 16:37
Can't test this currently as only have a super-admin not org-admin account on roadmap-stage but screengrab looks good so assume it is fine to close out

**Comment by sjDCC** [comment] 2018-10-05 17:10
Looks good. Closing out.

@briri I got an API error but I think this is part of config not a bug so will leave it

![api](https://user-images.githubusercontent.com/6169940/46549468-ff2e3480-c8c9-11e8-83f0-eb0159d978cb.PNG)

**Closed by sjDCC** 2018-10-05 17:10 UTC
Labels: admin, orgs
